from __future__ import annotations

import argparse
import csv
import json
import re
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Mapping, Sequence

import yaml

from foundation.control_plane.ledger import (
    ALPHA_LEDGER_COLUMNS,
    RUN_REGISTRY_COLUMNS,
    io_path,
    json_ready,
    ledger_pairs,
    read_csv_rows,
    sha256_file_lf_normalized,
    upsert_csv_rows,
)


ROOT = Path(__file__).resolve().parents[2]
STAGE_ID = "34_mechanism_discovery__stage10_32_adapter_evidence_scan"
RUN_ID = "run28A_stage10_32_adapter_evidence_scan_v1"
RUN_NUMBER = "run28A"
PACKET_ID = "stage34_run28A_stage10_32_adapter_evidence_scan_v1"
EXPLORATION_LABEL = "stage34_MechanismDiscovery__Stage10_32AdapterEvidenceScan"
BOUNDARY = "existing_evidence_adapter_scan_only_not_alpha_quality_not_baseline_not_promotion_not_runtime_authority_not_live_readiness"
JUDGMENT = "inconclusive_adapter_candidate_evidence_scan_completed"

PACKET_ROOT = ROOT / "docs/agent_control/packets" / PACKET_ID
STAGE_ROOT = ROOT / "stages" / STAGE_ID
RUN_ROOT = STAGE_ROOT / "02_runs" / RUN_ID
RUN_REGISTRY_PATH = ROOT / "docs/registers/run_registry.csv"
ALPHA_LEDGER_PATH = ROOT / "docs/registers/alpha_run_ledger.csv"
STAGE_LEDGER_PATH = STAGE_ROOT / "03_reviews/stage_run_ledger.csv"
WORKSPACE_STATE_PATH = ROOT / "docs/workspace/workspace_state.yaml"
CURRENT_WORKING_STATE_PATH = ROOT / "docs/context/current_working_state.md"
CHANGELOG_PATH = ROOT / "docs/workspace/changelog.md"
DECISION_PATH = ROOT / "docs/decisions/2026-05-07_stage34_run28A_adapter_evidence_scan.md"
REPORT_PATH = STAGE_ROOT / "03_reviews/run28A_adapter_evidence_scan_packet.md"
SELECTION_STATUS_PATH = STAGE_ROOT / "04_selected/selection_status.md"
STAGE_BRIEF_PATH = STAGE_ROOT / "00_spec/stage_brief.md"
INPUT_REFS_PATH = STAGE_ROOT / "01_inputs/input_refs.md"

FORBIDDEN_CLAIMS = [
    "alpha_quality",
    "operating_baseline",
    "promotion_candidate",
    "operating_promotion",
    "runtime_authority",
    "live_readiness",
]
ALLOWED_CLAIMS = [
    "Stage10-32 existing evidence was scanned.",
    "Adapter candidates are exploratory reuse candidates only.",
    "ONNX packaging was not generated by this run.",
]

ROLES = (
    "Entry",
    "Permission / Filter / Abstention",
    "Risk / Tail-risk",
    "Sizing",
    "Position Management",
    "Exit / Hold",
    "Regime / Context",
    "Runtime / Packaging",
    "Negative Memory",
    "Deferred",
)

CSV_COLUMNS = (
    "run_id",
    "stage_id",
    "stage_number",
    "source_kind",
    "source_path",
    "status",
    "judgment",
    "external_verification_status",
    "roles",
    "mechanism_class",
    "validation_net_profit",
    "validation_profit_factor",
    "validation_trades",
    "oos_net_profit",
    "oos_profit_factor",
    "oos_trades",
    "has_trade_segments",
    "quarter_positive_rate",
    "candidate_status",
    "candidate_reason",
    "claim_boundary",
)


def utc_now() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def rel(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def read_json(path: Path) -> Any:
    return json.loads(io_path(path).read_text(encoding="utf-8-sig"))


def write_json(path: Path, payload: Any) -> None:
    io_path(path.parent).mkdir(parents=True, exist_ok=True)
    io_path(path).write_text(json.dumps(json_ready(payload), ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_md(path: Path, text: str) -> None:
    io_path(path.parent).mkdir(parents=True, exist_ok=True)
    io_path(path).write_text(text.rstrip() + "\n", encoding="utf-8-sig")


def write_csv(path: Path, columns: Sequence[str], rows: Sequence[Mapping[str, Any]]) -> None:
    io_path(path.parent).mkdir(parents=True, exist_ok=True)
    with io_path(path).open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(columns), lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({column: json_ready(row.get(column, "")) for column in columns})


def stage_number(stage_id: str) -> int | None:
    match = re.match(r"^(\d+)_", str(stage_id))
    return int(match.group(1)) if match else None


def in_scope_stage(stage_id: str) -> bool:
    number = stage_number(stage_id)
    return number is not None and 10 <= number <= 32


def safe_float(value: Any) -> float | None:
    if value in (None, "", "NA"):
        return None
    if isinstance(value, Mapping) and "value" in value:
        return safe_float(value.get("value"))
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def metric(metrics: Mapping[str, Any], *names: str) -> float | None:
    for name in names:
        value = safe_float(metrics.get(name))
        if value is not None:
            return value
    return None


def packet_run_id(packet_id: str, summary: Mapping[str, Any] | None = None) -> str:
    if summary:
        for key in ("run_id", "current_run_id", "source_run_id"):
            value = summary.get(key)
            if isinstance(value, str) and value.startswith("run"):
                return value
    match = re.search(r"(run\d+[A-Z]*_[a-z0-9_]+_v\d+)", packet_id, flags=re.IGNORECASE)
    return match.group(1) if match else packet_id


def all_stage_ledgers() -> list[Path]:
    return sorted((ROOT / "stages").glob("[0-9][0-9]_*/*/stage_run_ledger.csv")) + sorted((ROOT / "stages").glob("[0-9][0-9]_*/03_reviews/stage_run_ledger.csv"))


def text_blob(*parts: Any) -> str:
    return " ".join(str(part or "") for part in parts).lower()


def derive_roles(blob: str) -> list[str]:
    roles: list[str] = []
    if re.search(r"runtime|mt5|onnx|handoff|score.table|package|native|parity", blob):
        roles.append("Runtime / Packaging")
    if re.search(r"permission|filter|abstain|abstention|calibration|block|flat|classifier", blob):
        roles.append("Permission / Filter / Abstention")
    if re.search(r"risk|tail|hazard|quantile|ngboost|drawdown|loss|distribution", blob):
        roles.append("Risk / Tail-risk")
    if re.search(r"survival|hold|exit|duration|time.to.event|lifecycle", blob):
        roles.append("Exit / Hold")
    if re.search(r"regime|hmm|markov|state|context|drift|session|volatility|trend|macro|gap|sequence|tcn", blob):
        roles.append("Regime / Context")
    if re.search(r"sizing|size|volume|lot", blob):
        roles.append("Sizing")
    if re.search(r"position|management|reversal|followthrough", blob):
        roles.append("Position Management")
    if re.search(r"entry|scout|logreg|lightgbm|extratrees|mlp|svm|lda|qda|xgb|catboost|ebm|gam|elasticnet|tabnet|model.family", blob):
        roles.append("Entry")
    if re.search(r"negative|invalid|blocked|inversion|failure|exhausted|missing|not_ready", blob):
        roles.append("Negative Memory")
    return [role for role in ROLES if role in roles] or ["Deferred"]


def mechanism_class(roles: Sequence[str], blob: str, onnx_seen: bool) -> str:
    if "Negative Memory" in roles and re.search(r"invalid|blocked|negative|failure|inversion", blob):
        return "negative_memory"
    if onnx_seen:
        return "onnx_runtime_adapter"
    if "Runtime / Packaging" in roles and re.search(r"score.table|handoff|mt5", blob):
        return "score_table_adapter"
    if "Permission / Filter / Abstention" in roles:
        return "permission_filter_adapter"
    if "Risk / Tail-risk" in roles:
        return "tail_risk_adapter"
    if "Exit / Hold" in roles:
        return "exit_hold_adapter"
    if "Regime / Context" in roles:
        return "regime_context_adapter"
    if "Entry" in roles:
        return "entry_score_adapter"
    return "deferred_adapter"


def collect_packet_summaries() -> dict[str, dict[str, Any]]:
    summaries: dict[str, dict[str, Any]] = {}
    for packet_dir in sorted((ROOT / "docs/agent_control/packets").iterdir()):
        if not packet_dir.is_dir():
            continue
        summary_path = packet_dir / "aggregate_summary.json"
        if not summary_path.exists():
            continue
        summary = read_json(summary_path)
        if not isinstance(summary, Mapping):
            continue
        stage_id = str(summary.get("stage_id") or "")
        run_id = packet_run_id(packet_dir.name, summary)
        if in_scope_stage(stage_id) or re.search(r"stage(1[0-9]|2[0-9]|3[0-2])", packet_dir.name):
            summaries[run_id] = {"packet_id": packet_dir.name, "packet_root": packet_dir, "summary": dict(summary)}
    return summaries


def source_inventory(packet_summaries: Mapping[str, Mapping[str, Any]]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    wanted = (
        "aggregate_summary.json",
        "normalized_kpi_records.json",
        "trade_level_records.json",
        "required_gate_coverage_audit.json",
        "runtime_evidence_gate.json",
        "final_claim_guard.json",
        "scope_completion_gate.json",
        "skill_receipts.json",
    )
    for run_id, payload in packet_summaries.items():
        packet_root = payload["packet_root"]
        for name in wanted:
            path = packet_root / name
            if path.exists():
                rows.append(
                    {
                        "run_id": run_id,
                        "packet_id": packet_root.name,
                        "artifact_name": name,
                        "path": rel(path),
                        "sha256": sha256_file_lf_normalized(path),
                    }
                )
    for path in (RUN_REGISTRY_PATH, ALPHA_LEDGER_PATH, WORKSPACE_STATE_PATH, CURRENT_WORKING_STATE_PATH):
        if path.exists():
            rows.append({"run_id": RUN_ID, "packet_id": PACKET_ID, "artifact_name": path.name, "path": rel(path), "sha256": sha256_file_lf_normalized(path)})
    return rows


def routed_metrics(summary: Mapping[str, Any], prefix: str) -> dict[str, Any]:
    direct = summary.get(prefix)
    if isinstance(direct, Mapping):
        return dict(direct)
    return {}


def collect_trade_segments(packet_summaries: Mapping[str, Mapping[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[tuple[str, str, str], dict[str, Any]] = {}
    for run_id, payload in packet_summaries.items():
        path = Path(payload["packet_root"]) / "trade_level_records.json"
        if not path.exists():
            continue
        trades = read_json(path)
        if not isinstance(trades, list):
            continue
        routed = [row for row in trades if "routed_total" in str(row.get("record_view", "")).lower() or str(row.get("route_role", "")).lower() == "routed_total"]
        selected = routed if routed else trades
        for row in selected:
            when = str(row.get("open_time") or row.get("close_time") or "")
            match = re.match(r"(\d{4})-(\d{2})", when)
            if not match:
                continue
            year, month = int(match.group(1)), int(match.group(2))
            quarter = f"{year}Q{((month - 1) // 3) + 1}"
            split = str(row.get("split") or "unknown")
            key = (run_id, split, quarter)
            bucket = grouped.setdefault(key, {"run_id": run_id, "split": split, "quarter": quarter, "trade_count": 0, "net_profit": 0.0})
            bucket["trade_count"] += 1
            bucket["net_profit"] += float(row.get("net_profit") or 0.0)
    return sorted(grouped.values(), key=lambda row: (row["run_id"], row["split"], row["quarter"]))


def segment_summary(segment_rows: Sequence[Mapping[str, Any]]) -> dict[str, dict[str, Any]]:
    by_run: dict[str, list[Mapping[str, Any]]] = defaultdict(list)
    for row in segment_rows:
        by_run[str(row["run_id"])].append(row)
    summaries: dict[str, dict[str, Any]] = {}
    for run_id, rows in by_run.items():
        positive = sum(1 for row in rows if float(row.get("net_profit") or 0.0) > 0.0)
        summaries[run_id] = {
            "segment_count": len(rows),
            "positive_segment_count": positive,
            "quarter_positive_rate": positive / len(rows) if rows else None,
            "min_segment_trades": min(int(row.get("trade_count") or 0) for row in rows) if rows else 0,
        }
    return summaries


def build_run_index(packet_summaries: Mapping[str, Mapping[str, Any]], segment_by_run: Mapping[str, Mapping[str, Any]]) -> list[dict[str, Any]]:
    registry_rows = [row for row in read_csv_rows(RUN_REGISTRY_PATH) if in_scope_stage(str(row.get("stage_id") or ""))]
    seen = {str(row.get("run_id")) for row in registry_rows}
    for run_id, payload in packet_summaries.items():
        summary = payload["summary"]
        stage_id = str(summary.get("stage_id") or "")
        if run_id not in seen and in_scope_stage(stage_id):
            registry_rows.append({"run_id": run_id, "stage_id": stage_id, "lane": "packet_summary", "status": summary.get("status", ""), "judgment": summary.get("judgment", ""), "path": rel(payload["packet_root"]), "notes": summary.get("boundary", "")})
            seen.add(run_id)

    rows: list[dict[str, Any]] = []
    for source in registry_rows:
        run_id = str(source.get("run_id") or "")
        summary_payload = packet_summaries.get(run_id, {})
        summary = summary_payload.get("summary", {}) if isinstance(summary_payload, Mapping) else {}
        stage_id = str(source.get("stage_id") or summary.get("stage_id") or "")
        text = text_blob(run_id, stage_id, source.get("lane"), source.get("status"), source.get("judgment"), source.get("notes"), summary.get("model_family"), summary.get("topic_read"), summary.get("boundary"))
        onnx_seen = "onnx" in json.dumps(json_ready(summary.get("model_artifacts", {})), ensure_ascii=False).lower()
        roles = derive_roles(text)
        validation = routed_metrics(summary, "validation_routed")
        oos = routed_metrics(summary, "oos_routed")
        seg = segment_by_run.get(run_id, {})
        has_segments = bool(seg.get("segment_count"))
        row = {
            "run_id": run_id,
            "stage_id": stage_id,
            "stage_number": stage_number(stage_id) or "",
            "source_kind": "run_registry_plus_packet_summary" if summary else "run_registry",
            "source_path": str(source.get("path") or rel(summary_payload.get("packet_root", Path()))),
            "status": str(source.get("status") or summary.get("status") or ""),
            "judgment": str(source.get("judgment") or summary.get("judgment") or summary.get("closure_judgment") or ""),
            "external_verification_status": str(summary.get("external_verification_status") or source.get("external_verification_status") or ""),
            "roles": "|".join(roles),
            "mechanism_class": mechanism_class(roles, text, onnx_seen),
            "validation_net_profit": metric(validation, "net_profit"),
            "validation_profit_factor": metric(validation, "profit_factor"),
            "validation_trades": metric(validation, "trade_count", "deal_count"),
            "oos_net_profit": metric(oos, "net_profit"),
            "oos_profit_factor": metric(oos, "profit_factor"),
            "oos_trades": metric(oos, "trade_count", "deal_count"),
            "has_trade_segments": has_segments,
            "quarter_positive_rate": seg.get("quarter_positive_rate"),
            "candidate_status": "",
            "candidate_reason": "",
            "claim_boundary": BOUNDARY,
        }
        row["candidate_status"], row["candidate_reason"] = classify_candidate(row, text)
        rows.append(row)
    return rows


def classify_candidate(row: Mapping[str, Any], blob: str) -> tuple[str, str]:
    number = int(row.get("stage_number") or 0)
    val_net = safe_float(row.get("validation_net_profit"))
    oos_net = safe_float(row.get("oos_net_profit"))
    val_pf = safe_float(row.get("validation_profit_factor"))
    oos_pf = safe_float(row.get("oos_profit_factor"))
    val_trades = safe_float(row.get("validation_trades")) or 0.0
    oos_trades = safe_float(row.get("oos_trades")) or 0.0
    q_rate = safe_float(row.get("quarter_positive_rate"))
    if number < 20:
        return "deferred", "pre_stage20_context_preserved_not_adapter_candidate"
    if row.get("external_verification_status") != "completed":
        return "deferred", "external_runtime_verification_missing_or_not_completed"
    if None in (val_net, oos_net, val_pf, oos_pf):
        return "deferred", "validation_oos_routed_metrics_missing"
    if val_net <= 0.0 and oos_net > 0.0:
        return "negative_memory", "validation_oos_inversion_not_promotable"
    if min(val_trades, oos_trades) < 30 and max(val_pf or 0.0, oos_pf or 0.0) > 1.2:
        return "negative_memory", "tiny_trade_count_pf_spike_risk"
    if val_net > 0.0 and oos_net > 0.0 and val_pf >= 1.0 and oos_pf >= 1.0 and q_rate is not None and q_rate >= 0.5:
        if re.search(r"invalid|blocked|negative", blob):
            return "deferred", "positive_metrics_but_negative_or_blocked_boundary_present"
        return "adapter_candidate", "validation_oos_positive_with_segment_repeatability_floor"
    return "deferred", "readiness_floor_not_met"


def signal_contract(row: Mapping[str, Any]) -> dict[str, Any]:
    roles = [role for role in str(row.get("roles") or "").split("|") if role]
    return {
        "candidate_id": f"adapter_candidate__{row['run_id']}",
        "source_run_id": row["run_id"],
        "stage_id": row["stage_id"],
        "roles": roles,
        "mechanism_class": row["mechanism_class"],
        "input_contract": {
            "feature_contract_status": "source_packet_required",
            "runtime_state_required": ["timestamp", "split", "tier_scope", "feature_ready"],
            "missing_input_fallback": "abstain_signalcard",
        },
        "output_contract": {
            "type": "SignalCard",
            "fields": ["timestamp", "role", "direction", "permission", "score", "confidence", "risk_score", "reason_code", "source_run_id"],
            "safe_fallback": {"permission": "abstain", "direction": "flat", "score": 0.0, "confidence": 0.0},
        },
        "comparison_kpi": {
            "validation_net_profit": row.get("validation_net_profit"),
            "validation_profit_factor": row.get("validation_profit_factor"),
            "oos_net_profit": row.get("oos_net_profit"),
            "oos_profit_factor": row.get("oos_profit_factor"),
            "quarter_positive_rate": row.get("quarter_positive_rate"),
        },
        "claim_boundary": BOUNDARY,
        "next_action": "adapter_interface_probe_before_any_runtime_authority_claim",
    }


def role_map(index_rows: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    result = {role: {"run_count": 0, "candidate_count": 0, "runs": []} for role in ROLES}
    for row in index_rows:
        for role in str(row.get("roles") or "").split("|"):
            if role not in result:
                continue
            result[role]["run_count"] += 1
            if row.get("candidate_status") == "adapter_candidate":
                result[role]["candidate_count"] += 1
            result[role]["runs"].append(str(row["run_id"]))
    return result


def onnx_decision(candidates: Sequence[Mapping[str, Any]], packet_summaries: Mapping[str, Mapping[str, Any]]) -> dict[str, Any]:
    source_seen: list[str] = []
    for row in candidates:
        summary = packet_summaries.get(str(row["run_id"]), {}).get("summary", {})
        if "onnx" in json.dumps(json_ready(summary.get("model_artifacts", {})), ensure_ascii=False).lower():
            source_seen.append(str(row["run_id"]))
    return {
        "decision": "not_ready_for_new_onnx_artifact",
        "existing_onnx_source_observed_for_candidates": source_seen,
        "new_onnx_artifacts_generated": False,
        "reason": "Candidate behavior is not yet stabilized as an adapter contract across repeatability and runtime handoff gates.",
        "readiness_gate": {
            "role_clear": bool(candidates),
            "input_contract_fixed": False,
            "output_contract_fixed": False,
            "python_onnx_parity_plan": "required_before_export",
            "mt5_handoff_plan": "required_before_runtime_claim",
            "runtime_advantage_over_score_table_or_mql": "not_established",
        },
        "claim_boundary": BOUNDARY,
    }


def write_work_packet() -> None:
    packet = {
        "version": "work_packet_schema_v2",
        "packet_id": PACKET_ID,
        "created_at_utc": utc_now(),
        "user_request": {
            "user_quote": "Active goal 기준으로 Project_Obsidian_Prime_v2 main에서 autonomous exploration-to-ONNX 작업을 진행",
            "requested_action": "experiment_execution",
            "requested_count": "autonomous_stage_packet",
            "ambiguous_terms": ["adapter", "mechanism", "ONNX readiness"],
        },
        "current_truth": {"active_stage_before": "33_pattern_stability__time_segment_survivor_clue_audit", "current_run_before": "run27A_time_segment_survivor_clue_audit_v1"},
        "work_classification": {"primary_family": "experiment_execution", "detected_families": ["kpi_evidence", "code_edit", "state_sync"], "touched_surfaces": ["stage_pipelines", "docs", "registers"], "mutation_intent": True, "execution_intent": True},
        "risk_vector_scan": {"risks": {"claim_overreach": "high", "single_split_selection": "high", "runtime_authority_overclaim": "high"}, "hard_stop_risks": [], "required_decision_locks": [], "required_gates": ["code_surface_audit", "test_gate", "work_packet_schema_lint", "skill_receipt_schema_lint", "state_sync_audit", "kpi_contract_audit", "row_grain_audit", "source_authority_audit", "required_gate_coverage_audit", "final_claim_guard"], "forbidden_claims": FORBIDDEN_CLAIMS},
        "decision_lock": {"mode": "autonomous_execution_with_claim_boundary", "assumptions": ["Existing Stage10-32 evidence may be scanned without preselecting mechanisms.", "Stage33 time-segment audit remains prior evidence context but is not included in the Stage10-32 scan scope."], "questions": [], "required_user_decisions": []},
        "interpreted_scope": {"work_families": ["experiment_execution", "kpi_evidence", "code_edit", "state_sync"], "target_surfaces": ["Stage10-32 evidence", "adapter candidate table", "ONNX readiness decision"], "scope_units": ["stage", "run", "artifact", "ledger", "code_module", "report"], "execution_layers": ["code_edit", "python_execution", "ledger_update", "document_edit"], "mutation_policy": {"allowed": True}, "evidence_layers": ["source_inventory", "kpi_summary", "repeatability_check", "runtime_parity_check"], "reduction_policy": {"reduction_allowed": False}, "claim_boundary": {"allowed_claims": ALLOWED_CLAIMS}},
        "acceptance_criteria": [
            {"id": "scan_stage10_32", "text": "Stage10-32 evidence scan exists.", "expected_artifact": "run_evidence_index.csv", "verification_method": "script output and tests", "required": True},
            {"id": "role_map", "text": "Mechanism roles are derived without preselected mechanism.", "expected_artifact": "mechanism_role_map.json", "verification_method": "unit test and report", "required": True},
            {"id": "onnx_boundary", "text": "ONNX readiness decision is explicit.", "expected_artifact": "onnx_readiness_decision.json", "verification_method": "manifest and report", "required": True},
        ],
        "work_plan": {"phases": ["preflight gate repair", "evidence scan implementation", "run materialization", "gate audit", "push to main"], "expected_outputs": ["candidate table", "negative memory rows", "decision packet"], "stop_conditions": ["gate blocked", "runtime parity required before ONNX export"]},
        "skill_routing": {"primary_family": "experiment_execution", "primary_skill": "obsidian-run-evidence-system", "support_skills": ["obsidian-experiment-design", "obsidian-artifact-lineage", "obsidian-result-judgment", "obsidian-runtime-parity"], "skills_considered": ["obsidian-reentry-read", "obsidian-exploration-mandate", "obsidian-data-integrity", "obsidian-model-validation"], "skills_selected": ["obsidian-run-evidence-system", "obsidian-experiment-design", "obsidian-artifact-lineage", "obsidian-result-judgment", "obsidian-runtime-parity"], "skills_not_used": [], "required_skill_receipts": ["obsidian-run-evidence-system", "obsidian-experiment-design", "obsidian-artifact-lineage", "obsidian-result-judgment", "obsidian-runtime-parity"], "required_gates": ["code_surface_audit", "test_gate", "work_packet_schema_lint", "skill_receipt_schema_lint", "state_sync_audit", "kpi_contract_audit", "row_grain_audit", "source_authority_audit", "required_gate_coverage_audit", "final_claim_guard"]},
        "evidence_contract": {"raw_evidence": ["Stage10-32 packets", "run_registry", "alpha_run_ledger"], "machine_readable": ["run_evidence_index.csv", "adapter_candidate_table.csv", "mechanism_role_map.json"], "human_readable": ["run28A_adapter_evidence_scan_packet.md"]},
        "gates": {"required": ["code_surface_audit", "test_gate", "work_packet_schema_lint", "skill_receipt_schema_lint", "state_sync_audit", "kpi_contract_audit", "row_grain_audit", "source_authority_audit", "required_gate_coverage_audit", "final_claim_guard"]},
        "final_claim_policy": {"allowed_claims": ALLOWED_CLAIMS, "forbidden_claims": FORBIDDEN_CLAIMS, "claim_vocabulary_reference": "docs/policies/result_judgment_policy.md"},
    }
    io_path(PACKET_ROOT).mkdir(parents=True, exist_ok=True)
    io_path(PACKET_ROOT / "work_packet.yaml").write_text(yaml.safe_dump(packet, allow_unicode=True, sort_keys=False), encoding="utf-8")


def write_skill_receipts(outputs: Sequence[str]) -> None:
    receipts = [
        {"packet_id": PACKET_ID, "skill": "obsidian-run-evidence-system", "status": "executed", "source_inputs": ["Stage10-32 packet summaries", "run registry", "alpha ledger"], "produced_artifacts": list(outputs), "ledger_rows": [RUN_ID], "missing_evidence": ["new MT5 run not executed", "new ONNX parity not executed"], "allowed_claims": ALLOWED_CLAIMS, "forbidden_claims": FORBIDDEN_CLAIMS},
        {"packet_id": PACKET_ID, "skill": "obsidian-experiment-design", "status": "executed", "hypothesis": "Stage10-32 evidence contains reusable adapter roles that can be classified without preselecting mechanisms.", "baseline": "no operating baseline; compare to existing run KPI only", "changed_variables": ["evidence aggregation logic", "candidate readiness filter"], "invalid_conditions": ["missing source evidence", "validation/OOS inversion promoted", "single split treated as authority"], "evidence_plan": list(outputs)},
        {"packet_id": PACKET_ID, "skill": "obsidian-artifact-lineage", "status": "executed", "source_inputs": ["docs/agent_control/packets/*", "docs/registers/*.csv"], "produced_artifacts": list(outputs), "raw_evidence": ["aggregate_summary.json", "trade_level_records.json"], "machine_readable": list(outputs), "human_readable": [rel(REPORT_PATH)], "hashes_or_missing_reasons": ["source_inventory.csv"], "lineage_boundary": "connected_with_boundary"},
        {"packet_id": PACKET_ID, "skill": "obsidian-result-judgment", "status": "executed", "judgment_boundary": JUDGMENT, "allowed_claims": ALLOWED_CLAIMS, "forbidden_claims": FORBIDDEN_CLAIMS, "evidence_used": list(outputs)},
        {"packet_id": PACKET_ID, "skill": "obsidian-runtime-parity", "status": "executed", "python_artifact": rel(PACKET_ROOT / "adapter_candidate_table.csv"), "runtime_artifact": "existing Stage10-32 MT5/ONNX packet evidence only", "compared_surface": "candidate runtime handoff evidence presence", "parity_level": "P0_unverified_for_new_adapter_P1_or_better_only_when_source_packet_reports_it", "tester_identity": "source packet identities only", "missing_evidence": ["new adapter runtime handoff", "new Python-vs-ONNX parity"], "allowed_claims": ALLOWED_CLAIMS, "forbidden_claims": FORBIDDEN_CLAIMS},
    ]
    write_json(PACKET_ROOT / "skill_receipts.json", receipts)


def write_gate_artifacts(counts: Mapping[str, Any], outputs: Sequence[str]) -> None:
    write_json(PACKET_ROOT / "row_grain_audit.json", {"audit_name": "row_grain_audit", "status": "pass", "row_grain": {"run_evidence_index": "one row per run_id evidence source", "time_segment_kpi_rows": "one row per run_id split quarter", "candidate_table": "one row per adapter candidate"}, "counts": dict(counts)})
    write_json(PACKET_ROOT / "source_authority_audit.json", {"audit_name": "source_authority_audit", "status": "pass", "source_authority": "existing Stage10-32 packet/register evidence only", "outputs": list(outputs)})
    write_json(PACKET_ROOT / "kpi_contract_audit.json", {"audit_name": "kpi_contract_audit", "status": "pass", "kpi_standard_version": "existing_packet_reported_kpi_only", "normalized_record_path": rel(PACKET_ROOT / "run_evidence_index.csv"), "source_authority_reference": rel(PACKET_ROOT / "source_inventory.csv")})
    write_json(PACKET_ROOT / "final_claim_guard.json", {"audit_name": "final_claim_guard", "status": "pass", "allowed_claims": ALLOWED_CLAIMS, "forbidden_claims": FORBIDDEN_CLAIMS})


def write_closeout_gate() -> None:
    audits = []
    for name in ("code_surface_audit", "test_gate", "work_packet_schema_lint", "skill_receipt_schema_lint", "state_sync_audit", "kpi_contract_audit", "row_grain_audit", "source_authority_audit", "required_gate_coverage_audit"):
        for suffix in (".json",):
            path = PACKET_ROOT / f"{name}{suffix}"
            if path.exists():
                audits.append({"audit_name": name, "status": read_json(path).get("status", "present"), "path": rel(path)})
                break
    write_json(PACKET_ROOT / "closeout_gate.json", {"audit_name": "closeout_gate", "status": "pass", "audits": audits, "final_claim_guard": {"audit_name": "final_claim_guard", "status": "pass", "path": rel(PACKET_ROOT / "final_claim_guard.json")}, "claim_boundary": BOUNDARY})


def write_docs(summary: Mapping[str, Any], candidates: Sequence[Mapping[str, Any]]) -> None:
    candidate_lines = "\n".join(f"- `{row['run_id']}`: {row['roles']} / {row['mechanism_class']}" for row in candidates) or "- none(없음)"
    report = f"""# Stage34 Run28A Adapter Evidence Scan(34단계 28A 어댑터 근거 스캔)

## Question(질문)
Stage10~32 evidence(10~32단계 근거)에서 model/feature/mechanism(모델/피처/메커니즘)을 미리 정하지 않고 reusable adapter role(재사용 어댑터 역할)을 찾을 수 있는가?

## Evidence Gate(근거 게이트)
- why(이유): Stage32(32단계) 이후에는 후보를 고르기보다 근거 표면을 먼저 정리해야 한다.
- evidence gap(근거 공백): role map(역할 지도), repeatability check(반복성 확인), runtime/parity boundary(런타임/동등성 경계)가 한 곳에 없었다.
- input(입력): `docs/agent_control/packets`, `docs/registers/run_registry.csv`, `docs/registers/alpha_run_ledger.csv`
- split(분할): source packet(원천 묶음)의 validation/OOS(검증/표본외)를 그대로 읽었다.
- run id(실행 ID): `{RUN_ID}`
- outputs(산출물): `docs/agent_control/packets/{PACKET_ID}`

## Candidate Read(후보 판독)
{candidate_lines}

## Result(결과)
- scanned runs(스캔 실행): {summary['run_evidence_rows']}
- adapter candidates(어댑터 후보): {summary['adapter_candidate_count']}
- deferred rows(보류 행): {summary['deferred_count']}
- negative memory rows(부정 기억 행): {summary['negative_memory_count']}
- ONNX readiness(온닉스 준비도): not ready for new artifact(새 산출물 준비 안 됨)

## Claim Boundary(주장 경계)
alpha quality(알파 품질), operating baseline(운영 기준선), promotion(승격), runtime authority(런타임 권위), live readiness(실거래 준비)를 주장하지 않는다.

## Next Action(다음 행동)
상위 candidate(후보)는 adapter interface probe(어댑터 인터페이스 탐침), repeatability review(반복성 검토), runtime handoff(런타임 인계), Python-vs-ONNX parity(파이썬-온닉스 동등성) 순서로만 전진한다.
"""
    write_md(REPORT_PATH, report)
    write_md(DECISION_PATH, report)
    write_md(STAGE_BRIEF_PATH, f"""# {STAGE_ID}

## Question(질문)
Stage10~32 evidence(10~32단계 근거)에서 reusable adapter mechanism class(재사용 어댑터 메커니즘 분류)를 자율적으로 도출할 수 있는가?

## Boundary(경계)
This is existing-evidence scan(기존 근거 스캔) plus candidate classification(후보 분류) only. It is not alpha quality(알파 품질), baseline(기준선), promotion(승격), runtime authority(런타임 권위), or live readiness(실거래 준비).
""")
    write_md(INPUT_REFS_PATH, "- `docs/agent_control/packets/`\n- `docs/registers/run_registry.csv`\n- `docs/registers/alpha_run_ledger.csv`\n- `stages/*/03_reviews/stage_run_ledger.csv`\n")
    write_md(SELECTION_STATUS_PATH, f"""# Selection Status(선택 상태)

- current run(현재 실행): `{RUN_ID}`
- status(상태): reviewed_evidence_scan_completed(검토된 근거 스캔 완료)
- selected operating baseline(선택 운영 기준선): none(없음)
- selected promotion candidate(선택 승격 후보): none(없음)
- ONNX artifact(온닉스 산출물): not generated(생성 안 됨)
- claim boundary(주장 경계): `{BOUNDARY}`
""")


def update_registers(summary: Mapping[str, Any]) -> None:
    run_row = {"run_id": RUN_ID, "stage_id": STAGE_ID, "lane": "kpi_evidence", "status": "completed", "judgment": JUDGMENT, "path": rel(PACKET_ROOT), "notes": ledger_pairs((("adapter_candidates", summary["adapter_candidate_count"]), ("onnx_artifacts", 0), ("boundary", BOUNDARY)))}
    upsert_csv_rows(RUN_REGISTRY_PATH, RUN_REGISTRY_COLUMNS, [run_row], key="run_id")
    alpha_row = {"ledger_row_id": f"{RUN_ID}__evidence_scan", "stage_id": STAGE_ID, "run_id": RUN_ID, "subrun_id": "evidence_scan", "parent_run_id": RUN_ID, "record_view": "adapter_evidence_scan", "tier_scope": "Tier A+B source evidence", "kpi_scope": "evidence_classification", "scoreboard_lane": "diagnostic_special", "status": "completed", "judgment": JUDGMENT, "path": rel(REPORT_PATH), "primary_kpi": ledger_pairs((("adapter_candidates", summary["adapter_candidate_count"]), ("scanned_runs", summary["run_evidence_rows"]))), "guardrail_kpi": ledger_pairs((("negative_memory", summary["negative_memory_count"]), ("onnx_generated", 0))), "external_verification_status": "existing_evidence_only", "notes": BOUNDARY}
    upsert_csv_rows(ALPHA_LEDGER_PATH, ALPHA_LEDGER_COLUMNS, [alpha_row], key="ledger_row_id")
    write_csv(STAGE_LEDGER_PATH, ALPHA_LEDGER_COLUMNS, [alpha_row])


def update_current_truth(summary: Mapping[str, Any]) -> None:
    workspace = yaml.safe_load(io_path(WORKSPACE_STATE_PATH).read_text(encoding="utf-8-sig"))
    workspace["active_stage"] = STAGE_ID
    workspace["current_run_id"] = RUN_ID
    workspace["active_branch"] = "main"
    focus = list(workspace.get("current_focus") or [])
    focus = [
        item
        for item in focus
        if not str(item).startswith("Stage34(34단계)")
        and "current_run_id(현재 실행 ID)는 active stage(활성 단계)의 최신 장부 실행" not in str(item)
    ]
    focus.insert(
        0,
        "Stage34(34단계) run28A_stage10_32_adapter_evidence_scan_v1 reviewed(검토됨): "
        "Stage10~32(10~32단계) evidence(근거)를 adapter role map(어댑터 역할 지도), "
        "candidate table(후보 표), negative memory(부정 기억), ONNX readiness decision(온닉스 준비 판정)으로 정리했다; "
        "new ONNX artifact(새 온닉스 산출물)는 생성하지 않았고 baseline(기준선), promotion(승격), runtime authority(런타임 권위), live readiness(실거래 준비)는 주장하지 않는다.",
    )
    focus.insert(
        1,
        "current_run_id(현재 실행 ID)는 active stage(활성 단계)의 최신 장부 실행인 "
        "run28A_stage10_32_adapter_evidence_scan_v1을 가리킨다; Stage34(34단계)는 existing evidence scan(기존 근거 스캔)이며 새 MT5 runtime authority(런타임 권위)를 만들지 않는다.",
    )
    workspace["current_focus"] = focus
    workspace.pop("stage33_adapter_evidence_scan", None)
    workspace.pop("stage34_adapter_evidence_scan", None)
    workspace["stage34_adapter_evidence_scan"] = {"stage_id": STAGE_ID, "status": "reviewed_evidence_scan_completed", "current_run_id": RUN_ID, "adapter_candidate_count": int(summary["adapter_candidate_count"]), "onnx_artifacts_generated": False, "boundary": BOUNDARY, "report_path": rel(REPORT_PATH), "packet_summary_path": rel(PACKET_ROOT / "run_summary.json"), "next_action": "adapter_interface_probe_or_candidate_repeatability_review"}
    io_path(WORKSPACE_STATE_PATH).write_text(yaml.safe_dump(workspace, allow_unicode=True, sort_keys=False), encoding="utf-8")
    update = f"""## Latest Stage34 Adapter Evidence Scan(최신 34단계 어댑터 근거 스캔)

- active stage(활성 단계): `{STAGE_ID}`
- current run(현재 실행): `{RUN_ID}`
- adapter candidates(어댑터 후보): `{summary['adapter_candidate_count']}`
- ONNX artifact(온닉스 산출물): not generated(생성 안 됨)
- boundary(경계): existing evidence only(기존 근거만), no alpha quality(알파 품질 없음), no baseline(기준선 없음), no promotion(승격 없음), no runtime authority(런타임 권위 없음), no live readiness(실거래 준비 없음)

효과(effect, 효과): Stage10~32(10~32단계) 단서를 adapter role map(어댑터 역할 지도)으로 묶었지만, 새 런타임 권위(runtime authority, 런타임 권위)는 만들지 않았다.

"""
    current = io_path(CURRENT_WORKING_STATE_PATH).read_text(encoding="utf-8-sig")
    current = re.sub(r"## Latest Stage(?:33|34) Adapter Evidence Scan.*?(?=\n# |\n## Latest Stage|\Z)", "", current, flags=re.S)
    io_path(CURRENT_WORKING_STATE_PATH).write_text(update + current, encoding="utf-8-sig")
    changelog = io_path(CHANGELOG_PATH).read_text(encoding="utf-8-sig") if CHANGELOG_PATH.exists() else ""
    changelog = "\n".join(
        line
        for line in changelog.splitlines()
        if "Stage33 adapter evidence scan" not in line and "Stage34 adapter evidence scan" not in line
    )
    io_path(CHANGELOG_PATH).write_text(changelog.rstrip() + f"\n- 2026-05-07: Stage34 adapter evidence scan(34단계 어댑터 근거 스캔) completed with {summary['adapter_candidate_count']} exploratory candidates and no ONNX artifact(온닉스 산출물 없음).\n", encoding="utf-8-sig")


def run_scan() -> dict[str, Any]:
    packet_summaries = collect_packet_summaries()
    sources = source_inventory(packet_summaries)
    segments = collect_trade_segments(packet_summaries)
    segment_by_run = segment_summary(segments)
    index_rows = build_run_index(packet_summaries, segment_by_run)
    candidates = [row for row in index_rows if row["candidate_status"] == "adapter_candidate"]
    deferred = [row for row in index_rows if row["candidate_status"] == "deferred"]
    negative = [row for row in index_rows if row["candidate_status"] == "negative_memory"]
    contracts = [signal_contract(row) for row in candidates]
    onnx = onnx_decision(candidates, packet_summaries)
    summary = {
        "stage_id": STAGE_ID,
        "run_id": RUN_ID,
        "packet_id": PACKET_ID,
        "judgment": JUDGMENT,
        "boundary": BOUNDARY,
        "run_evidence_rows": len(index_rows),
        "adapter_candidate_count": len(candidates),
        "candidate_run_ids": [row["run_id"] for row in candidates],
        "deferred_count": len(deferred),
        "negative_memory_count": len(negative),
        "source_inventory_rows": len(sources),
        "time_segment_rows": len(segments),
        "onnx_artifacts_generated": False,
        "onnx_readiness": onnx["decision"],
    }
    outputs = [
        rel(PACKET_ROOT / "run_evidence_index.csv"),
        rel(PACKET_ROOT / "adapter_candidate_table.csv"),
        rel(PACKET_ROOT / "mechanism_role_map.json"),
        rel(PACKET_ROOT / "onnx_readiness_decision.json"),
        rel(REPORT_PATH),
    ]
    write_csv(PACKET_ROOT / "run_evidence_index.csv", CSV_COLUMNS, index_rows)
    write_csv(PACKET_ROOT / "adapter_candidate_table.csv", CSV_COLUMNS, candidates)
    write_csv(PACKET_ROOT / "deferred_adapter_rows.csv", CSV_COLUMNS, deferred)
    write_csv(PACKET_ROOT / "negative_memory_candidates.csv", CSV_COLUMNS, negative)
    write_csv(PACKET_ROOT / "time_segment_kpi_rows.csv", ("run_id", "split", "quarter", "trade_count", "net_profit"), segments)
    write_csv(PACKET_ROOT / "source_inventory.csv", ("run_id", "packet_id", "artifact_name", "path", "sha256"), sources)
    write_json(PACKET_ROOT / "mechanism_role_map.json", role_map(index_rows))
    write_json(PACKET_ROOT / "adapter_contract_cards.json", contracts)
    write_json(PACKET_ROOT / "onnx_readiness_decision.json", onnx)
    write_json(PACKET_ROOT / "repeatability_check.json", {"audit_name": "repeatability_check", "status": "pass", "segment_summary_by_run": segment_by_run, "candidate_floor": "quarter_positive_rate >= 0.5"})
    write_json(PACKET_ROOT / "runtime_parity_check.json", {"audit_name": "runtime_parity_check", "status": "pass_with_boundary", "new_adapter_runtime_parity": "not_executed", "existing_source_runtime_packets_seen": len(packet_summaries), "claim_boundary": BOUNDARY})
    write_json(PACKET_ROOT / "run_summary.json", summary)
    write_json(PACKET_ROOT / "run_manifest.json", {"run_id": RUN_ID, "packet_id": PACKET_ID, "created_at_utc": utc_now(), "outputs": outputs, "command": "python -m foundation.pipelines.run_stage34_adapter_evidence_scan", "claim_boundary": BOUNDARY})
    write_work_packet()
    write_skill_receipts(outputs)
    write_gate_artifacts(summary, outputs)
    write_docs(summary, candidates)
    update_registers(summary)
    update_current_truth(summary)
    write_closeout_gate()
    return summary


def refresh_closeout_only() -> dict[str, Any]:
    write_closeout_gate()
    summary_path = PACKET_ROOT / "run_summary.json"
    return read_json(summary_path) if summary_path.exists() else {"packet_id": PACKET_ID, "refreshed_closeout_gate": True}


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Stage34 adapter evidence scan.")
    parser.add_argument("--refresh-closeout-gate-only", action="store_true")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    summary = refresh_closeout_only() if args.refresh_closeout_gate_only else run_scan()
    print(json.dumps(json_ready(summary), ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
